name: Test Action
on:
  repository_dispatch:
    types: webhook
  

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        
      - name: execute
        run: echo "Hello world"
        shell: bash

      - name: payload processing
        run: | 
          echo ":: set-env
          name=PAYLOAD::${{toJSON(github.event.client_payload)}}
          "
        
      - name: Set up NodeJs environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          
      - name: check Version
        run: node --version
        
      - name: Install dependencies
        run: npm install

      - name: Run node file
        run: node index.js

