name: Test Action
on:
  repository_dispatch:
    types: webhook
  

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        
      - name: execute
        run: echo "Hello world"
        shell: bash
        
      - name: Set up NodeJs environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          
      - name: check Version
        run: node --version
        
      - name: Install Jq
        uses: dcarbone/install-jq-action@v2.0.2

      - name: process Webhook
        id: webhook
        run: |
          input_data=${{toJSON(github.event.client_payload.name)}}
          key_value=$(echo $input_data | jq -r .key)

          echo 'Payload -$key_value'
