name: Test Action
on:
  repository_dispatch:
    types: webhook
  

jobs:
  hello:
    runs-on: ubuntu-latest

    env: 
      PAYLOAD_DATA: ${{toJSON(github.event.client_payload)}}
      
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        
      - name: Set up NodeJs environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          
      - name: check Version
        run: node --version

      - name : Creating Package.Json
        run: npm init -y
        
      - name: Install dependencies
        run: npm install

      - name: Run node file
        run: node index.js

